[package]
name = "patent-kit"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
rust-embed = "8.0"

[[bin]]
name = "ftoc"
path = "src/bin/ftoc.rs"
