[tools]
node = "20"
python = "3.11"

[tasks]
fmt = { description = "Format files with prettier", run = "npx prettier --write ." }
pre-commit = { description = "Pre-commit hook to format files", depends = ["fmt"] }
